#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
#
Name     : perl-SQL-SplitStatement
Version  : 1.00023
Release  : 13
URL      : https://cpan.metacpan.org/authors/id/V/VE/VEESH/SQL-SplitStatement-1.00023.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/V/VE/VEESH/SQL-SplitStatement-1.00023.tar.gz
Summary  : 'Split any SQL code into atomic statements'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-SQL-SplitStatement-bin = %{version}-%{release}
Requires: perl-SQL-SplitStatement-license = %{version}-%{release}
Requires: perl-SQL-SplitStatement-man = %{version}-%{release}
Requires: perl-SQL-SplitStatement-perl = %{version}-%{release}
Requires: perl(SQL::Tokenizer)
BuildRequires : buildreq-cpan
BuildRequires : perl(Algorithm::Diff)
BuildRequires : perl(Class::Accessor::Fast)
BuildRequires : perl(Exporter::Tiny)
BuildRequires : perl(List::MoreUtils)
BuildRequires : perl(Regexp::Common)
BuildRequires : perl(Test::Differences)
BuildRequires : perl(Test::Exception)
BuildRequires : perl(Text::Diff)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
NAME
SQL::SplitStatement - Split any SQL code into atomic statements
SYNOPSIS
# Multiple SQL statements in a single string
my $sql_code = <<'SQL';
CREATE TABLE parent(a, b, c   , d    );
CREATE TABLE child (x, y, "w;", "z;z");
/* C-style comment; */
CREATE TRIGGER "check;delete;parent;" BEFORE DELETE ON parent WHEN
EXISTS (SELECT 1 FROM child WHERE old.a = x AND old.b = y)
BEGIN
SELECT RAISE(ABORT, 'constraint failed;'); -- Inline SQL comment
END;
-- Standalone SQL; comment; with semicolons;
INSERT INTO parent (a, b, c, d) VALUES ('pippo;', 'pluto;', NULL, NULL);
SQL

use SQL::SplitStatement;

my $sql_splitter = SQL::SplitStatement->new;
my @statements = $sql_splitter->split($sql_code);

# @statements now is:
#
# (
#     'CREATE TABLE parent(a, b, c   , d    )',
#     'CREATE TABLE child (x, y, "w;", "z;z")',
#     'CREATE TRIGGER "check;delete;parent;" BEFORE DELETE ON parent WHEN
#     EXISTS (SELECT 1 FROM child WHERE old.a = x AND old.b = y)
# BEGIN
#     SELECT RAISE(ABORT, \'constraint failed;\');
# END',
#     'INSERT INTO parent (a, b, c, d) VALUES (\'pippo;\', \'pluto;\', NULL, NULL)'
# )

%package bin
Summary: bin components for the perl-SQL-SplitStatement package.
Group: Binaries
Requires: perl-SQL-SplitStatement-license = %{version}-%{release}

%description bin
bin components for the perl-SQL-SplitStatement package.


%package dev
Summary: dev components for the perl-SQL-SplitStatement package.
Group: Development
Requires: perl-SQL-SplitStatement-bin = %{version}-%{release}
Provides: perl-SQL-SplitStatement-devel = %{version}-%{release}
Requires: perl-SQL-SplitStatement = %{version}-%{release}

%description dev
dev components for the perl-SQL-SplitStatement package.


%package license
Summary: license components for the perl-SQL-SplitStatement package.
Group: Default

%description license
license components for the perl-SQL-SplitStatement package.


%package man
Summary: man components for the perl-SQL-SplitStatement package.
Group: Default

%description man
man components for the perl-SQL-SplitStatement package.


%package perl
Summary: perl components for the perl-SQL-SplitStatement package.
Group: Default
Requires: perl-SQL-SplitStatement = %{version}-%{release}

%description perl
perl components for the perl-SQL-SplitStatement package.


%prep
%setup -q -n SQL-SplitStatement-1.00023
cd %{_builddir}/SQL-SplitStatement-1.00023

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-SQL-SplitStatement
cp %{_builddir}/SQL-SplitStatement-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-SQL-SplitStatement/354a709ad184caf5bd314c07d6dd295f2dced181 || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/sql-split

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/SQL::SplitStatement.3
/usr/share/man/man3/SQL::SplitStatement::Tokenizer.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-SQL-SplitStatement/354a709ad184caf5bd314c07d6dd295f2dced181

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/sql-split.1

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
